### ISSUE TITLE
Self-host?

### ISSUE THREAD

**Issue by SeaDude** [richorama/azure-maps-admin-portal#2]
Hello,

Awesome tool! Thanks for making it available. Is there a way to self-host the admin-portal? If so, could you give me some pointers on how to accomplish that?

Thank you!

**Comment by richorama** [comment]
Hi @SeaDude, sorry for not seeing your issue sooner. I have added instructions for self hosting in the readme. Thanks.

**Comment by SeaDude** [comment]
All good @richorama ! Thanks for updating the README.md. I'll try my hand at self hosting this great tool.

**Comment by SeaDude** [comment]
Noice! I was able to get it up and running.

**Comment by richorama** [comment]
cool :¬)

glad you're finding it useful, please let me know if you can think of anything to improve.

**Comment by SeaDude** [comment]
The two biggest things I believe people need in a tool like this are:
1. Ability to add a feature to the map (point/polygon/shape/line) and add `properties` to said feature.
  - This would in turn update the `.geojson` file stored in Azure Maps Data Services
2. Ability to hover over a feature (point/polygon/shape/line) and view **AND** edit its `properties`.
  - This would in turn update the `.geojson` file stored in Azure Maps Data Services
Something similiar to [GeoJSON.io](http://geojson.io/#map=2/20.0/0.0). There is an Azure Maps SDK sample [here](https://azuremapscodesamples.azurewebsites.net/Drawing%20Tools%20Module/Get%20drawn%20shapes%20from%20drawing%20manager.html) that has *some* of this functionality.
My two cents :)

**Comment by richorama** [comment]
good ideas - thanks :¬)
